"""Command-to-handler registry."""

from termkeeper.presentation.cli.handlers.capture import (
    handle_add,
    handle_discard,
    handle_history,
    handle_inbox,
    handle_occurrence_edit,
    handle_occurrences,
    handle_reopen,
    handle_resolve,
    handle_stats,
    handle_unresolve,
)
from termkeeper.presentation.cli.handlers.config import handle_config
from termkeeper.presentation.cli.handlers.meaning import (
    handle_alias,
    handle_delete,
    handle_edit,
    handle_meanings,
    handle_merge,
    handle_purge,
    handle_restore,
    handle_search,
    handle_show,
    handle_trash,
    handle_unalias,
)
from termkeeper.presentation.cli.handlers.metadata import (
    handle_favorite,
    handle_reference_add,
    handle_reference_edit,
    handle_reference_remove,
    handle_references,
    handle_relate,
    handle_related,
    handle_tag,
    handle_tags,
    handle_unfavorite,
    handle_unrelate,
    handle_untag,
)
from termkeeper.presentation.cli.handlers.transfer import (
    handle_export,
    handle_import,
    handle_init,
)
from termkeeper.presentation.cli.types import CommandHandler

HANDLERS: dict[str, CommandHandler] = {
    "init": handle_init,
    "add": handle_add,
    "inbox": handle_inbox,
    "history": handle_history,
    "occurrences": handle_occurrences,
    "occurrence-edit": handle_occurrence_edit,
    "stats": handle_stats,
    "resolve": handle_resolve,
    "unresolve": handle_unresolve,
    "search": handle_search,
    "discard": handle_discard,
    "reopen": handle_reopen,
    "show": handle_show,
    "alias": handle_alias,
    "unalias": handle_unalias,
    "delete": handle_delete,
    "trash": handle_trash,
    "restore": handle_restore,
    "purge": handle_purge,
    "merge": handle_merge,
    "tag": handle_tag,
    "untag": handle_untag,
    "tags": handle_tags,
    "favorite": handle_favorite,
    "unfavorite": handle_unfavorite,
    "relate": handle_relate,
    "unrelate": handle_unrelate,
    "related": handle_related,
    "reference-add": handle_reference_add,
    "reference-edit": handle_reference_edit,
    "reference-remove": handle_reference_remove,
    "references": handle_references,
    "edit": handle_edit,
    "meanings": handle_meanings,
    "config": handle_config,
    "export": handle_export,
    "import": handle_import,
}
